// frontend/js/components/IdeaWorkspace.js

// This class will handle the main "chat" modal. All logic for displaying content, chatting, updating status, and deleting nodes will live here.

class IdeaWorkspace {
  constructor(apiService) {
    console.log("IdeaWorkspace: Initializing...");
    this.api = apiService;
    this.isOpen = false;
    this.currentNode = null;
    this.conversationHistory = [];

    // DOM Element References
    this.modal = document.getElementById("idea-modal");
    this.title = document.getElementById("modal-title");
    this.generatedBy = document.getElementById("modal-generated-by");
    this.attachmentContainer = document.getElementById(
      "modal-attachment-container"
    );
    this.attachmentImage = document.getElementById("modal-attachment-image");
    this.textContent = document.getElementById("modal-text-content");
    this.chatMessages = document.getElementById("chat-messages");
    this.chatForm = document.getElementById("chat-form");
    this.chatInput = document.getElementById("chat-input");
    this.closeButton = document.getElementById("modal-close-button");
    this.deleteButton = document.getElementById("modal-delete-button");
    this.statusButtonsContainer = document.querySelector(".status-controls");

    this.onNodeDeletedCallback = null;

    this._addEventListeners();
    console.log("IdeaWorkspace: Initialized.");
  }

  _addEventListeners() {
    this.closeButton.addEventListener("click", () => this.close());
    this.deleteButton.addEventListener("click", () => this._deleteNode());
    this.chatForm.addEventListener("submit", (e) => this._sendMessage(e));
    this.statusButtonsContainer.addEventListener("click", (e) => {
      if (e.target.classList.contains("status-btn")) {
        this._updateStatus(e.target.dataset.status);
      }
    });
  }

  async open(node) {
    console.log(`IdeaWorkspace: Opening for node ID: ${node.id()}`);
    this.currentNode = node;
    this.modal.style.display = "flex";
    this.isOpen = true;

    // Render content
    this.title.textContent = this.currentNode.data("label");
    this._renderProvenance();
    this._renderAttachment();
    this._renderTextContent();
    this._updateStatusButtons();

    // Fetch and render chat history
    await this._loadChatHistory();
  }

  close() {
    console.log("IdeaWorkspace: Closing...");
    this.modal.style.display = "none";
    this.isOpen = false;
    this.currentNode = null;
    this.conversationHistory = [];
  }

  _renderProvenance() {
    const generatedByText = this.currentNode.data("generated_by");
    this.generatedBy.textContent = generatedByText
      ? `Generated by: ${generatedByText}`
      : "";
    this.generatedBy.style.display = generatedByText ? "block" : "none";
  }

  _renderAttachment() {
    const path = this.currentNode.data("attachment_path");
    if (path) {
      this.attachmentImage.src = path;
      this.attachmentContainer.style.display = "block";
    } else {
      this.attachmentContainer.style.display = "none";
    }
  }

  _renderTextContent() {
    const text = this.currentNode.data("fullText");
    if (text && text.trim() !== "") {
      this.textContent.textContent = text;
      this.textContent.style.display = "block";
    } else {
      this.textContent.style.display = "none";
    }
  }

  async _loadChatHistory() {
    this.chatMessages.innerHTML =
      '<div class="chat-message model">Loading history...</div>';
    try {
      this.conversationHistory = await this.api.getChatHistory(
        this.currentNode.id()
      );
      this.chatMessages.innerHTML = "";
      this.conversationHistory.forEach((msg) => {
        this._appendChatMessage(msg.parts[0], msg.role, msg.generated_by);
      });
    } catch (error) {
      console.error("IdeaWorkspace: Failed to load chat history.", error);
      this.chatMessages.innerHTML =
        '<div class="chat-message model">Could not load history.</div>';
    }
  }

  async _sendMessage(event) {
    event.preventDefault();
    event.stopPropagation();
    const userMessage = this.chatInput.value;
    if (!userMessage.trim()) return;

    this._appendChatMessage(userMessage, "user");
    this.chatInput.value = "";
    const submitButton = this.chatForm.querySelector("button");
    submitButton.disabled = true;

    try {
      const payload = {
        nodeId: this.currentNode.id(),
        nodeContext: this.currentNode.data("fullText"),
        history: this.conversationHistory,
        userMessage: userMessage,
      };
      const data = await this.api.sendMessage(payload);
      this._appendChatMessage(data.response, "model", data.model_name);

      // Update in-memory history
      this.conversationHistory.push({ role: "user", parts: [userMessage] });
      this.conversationHistory.push({
        role: "model",
        parts: [data.response],
        generated_by: data.model_name,
      });
    } catch (error) {
      console.error("IdeaWorkspace: Chat error:", error);
      this._appendChatMessage(
        `Sorry, an error occurred: ${error.message}`,
        "model"
      );
    } finally {
      submitButton.disabled = false;
    }
  }

  _appendChatMessage(text, role, modelName = null) {
    const messageContainer = document.createElement("div");
    messageContainer.classList.add("chat-message", role);
    if (role === "model" && modelName) {
      const header = document.createElement("div");
      header.classList.add("message-header");
      header.textContent = modelName;
      messageContainer.appendChild(header);
    }
    const content = document.createElement("div");
    content.textContent = text;
    messageContainer.appendChild(content);
    this.chatMessages.appendChild(messageContainer);
    this.chatMessages.scrollTop = this.chatMessages.scrollHeight;
  }

  async _updateStatus(newStatus) {
    if (!this.currentNode) return;
    try {
      await this.api.updateNodeStatus(this.currentNode.id(), newStatus);
      this.currentNode.data("status", newStatus); // Update Cytoscape data
      const baseClass = this.currentNode.hasClass("user-node")
        ? "user-node"
        : "ai-node";
      const attachmentClass = this.currentNode.hasClass("has-attachment")
        ? " has-attachment"
        : "";
      this.currentNode.classes(
        `${baseClass} status-${newStatus}${attachmentClass}`
      );
      this._updateStatusButtons();
    } catch (error) {
      console.error("IdeaWorkspace: Failed to update status.", error);
      alert("Could not update status.");
    }
  }

  _updateStatusButtons() {
    const currentStatus = this.currentNode.data("status");
    this.statusButtonsContainer
      .querySelectorAll(".status-btn")
      .forEach((btn) => {
        btn.classList.toggle("active", btn.dataset.status === currentStatus);
      });
  }

  async _deleteNode() {
    if (!this.currentNode) return;
    if (
      confirm("Are you sure you want to delete this node and all its children?")
    ) {
      try {
        await this.api.deleteNode(this.currentNode.id());
        this.close();
        if (this.onNodeDeletedCallback) {
          this.onNodeDeletedCallback();
        }
      } catch (error) {
        console.error("IdeaWorkspace: Failed to delete node.", error);
        alert("Could not delete the node branch.");
      }
    }
  }
}
